version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - REPOSITORY_URI=374909061409.dkr.ecr.ap-northeast-1.amazonaws.com/microservices-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG_ADSERVICE=adservice
      - IMAGE_TAG_CARTSERVICE=cartservice
      - IMAGE_TAG_CHECKOUTSERVICE=checkoutservice
      - IMAGE_TAG_CURRENCYSERVICE=currencyservice
      - IMAGE_TAG_EMAILSERVICE=emailservice
      - IMAGE_TAG_FRONTEND=frontend
      - IMAGE_TAG_LOADGENERATOR=loadgenerator
      - IMAGE_TAG_PAYMENTSERVICE=paymentservice
      - IMAGE_TAG_PRODUCTCATALOGSERVICE=productcatalogservice
      - IMAGE_TAG_RECOMMENDATIONSERVICE=recommendationservice
      - IMAGE_TAG_SHIPPINGSERVICE=shippingservice
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build src/adservice -t $REPOSITORY_URI:adservice
      - docker tag $REPOSITORY_URI:adservice $REPOSITORY_URI:$IMAGE_TAG_ADSERVICE
      - docker build src/cartservice/src -t $REPOSITORY_URI:cartservice
      - docker tag $REPOSITORY_URI:cartservice $REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE
      - docker build src/checkoutservice -t $REPOSITORY_URI:checkoutservice
      - docker tag $REPOSITORY_URI:checkoutservice $REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE
      - docker build src/currencyservice -t $REPOSITORY_URI:currencyservice
      - docker tag $REPOSITORY_URI:currencyservice $REPOSITORY_URI:$IMAGE_TAG_CURRENCYSERVICE
      - docker build src/frontend -t $REPOSITORY_URI:frontend
      - docker tag $REPOSITORY_URI:frontend $REPOSITORY_URI:$IMAGE_TAG_FRONTEND
      - docker build src/loadgenerator -t $REPOSITORY_URI:loadgenerator
      - docker tag $REPOSITORY_URI:loadgenerator $REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR
      - docker build src/paymentservice -t $REPOSITORY_URI:paymentservice
      - docker tag $REPOSITORY_URI:paymentservice $REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE
      - docker build src/productcatalogservice -t $REPOSITORY_URI:productcatalogservice
      - docker tag $REPOSITORY_URI:productcatalogservice $REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE
      - docker build src/recommendationservice -t $REPOSITORY_URI:recommendationservice
      - docker tag $REPOSITORY_URI:recommendationservice $REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE
      - docker build src/shippingservice -t $REPOSITORY_URI:shippingservice
      - docker tag $REPOSITORY_URI:shippingservice $REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE
      - docker build src/emailservice -t $REPOSITORY_URI:emailservice
      - docker tag $REPOSITORY_URI:emailservice $REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:adservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_ADSERVICE
      - docker push $REPOSITORY_URI:cartservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE
      - docker push $REPOSITORY_URI:checkoutservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE
      - docker push $REPOSITORY_URI:currencyservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_CURRENCYSERVICE
      - docker push $REPOSITORY_URI:emailservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE
      - docker push $REPOSITORY_URI:frontend
      - docker push $REPOSITORY_URI:$IMAGE_TAG_FRONTEND
      - docker push $REPOSITORY_URI:loadgenerator
      - docker push $REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR
      - docker push $REPOSITORY_URI:paymentservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE
      - docker push $REPOSITORY_URI:productcatalogservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE
      - docker push $REPOSITORY_URI:recommendationservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE
      - docker push $REPOSITORY_URI:shippingservice
      - docker push $REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE
      - export AWS_ACCESS_KEY_ID='${ssm:/microservices/accesskey}'
      - export AWS_SECRET_ACCESS_KEY='${ssm:/microservices/accesskeysecret}'
      - aws eks update-kubeconfig --name eks-microservices-demo-cluster --region ap-northeast-1
      - kubectl apply -f release/kubernetes-manifests.yaml
