version: 0.2
phases:
  install:
    commands:
      # Install kubectl
      - curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.10/2019-06-21/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - kubectl version --short --client
      # Install Iam Authenticator
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
      - aws-iam-authenticator help
      # Configure kubectl
      - aws eks --region ap-northeast-1 update-kubeconfig --name microservises-demo-deployment-cluster
      # Install the AWS CLI
      - apt-get update && apt-get install -y awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - REPOSITORY_URI=374909061409.dkr.ecr.ap-northeast-1.amazonaws.com/microservices-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TAG="$(date +%Y-%m-%d.%H.%M.%S)"
      - echo This is the Tag
      - echo $TAG
      - IMAGE_TAG_ADSERVICE=adservice
      - IMAGE_TAG_CARTSERVICE=cartservice
      - IMAGE_TAG_CHECKOUTSERVICE=checkoutservice
      - IMAGE_TAG_CURRENCYSERVICE=currencyservice
      - IMAGE_TAG_EMAILSERVICE=emailservice
      - IMAGE_TAG_FRONTEND=frontend$TAG
      - IMAGE_TAG_LOADGENERATOR=loadgenerator
      - IMAGE_TAG_PAYMENTSERVICE=paymentservice
      - IMAGE_TAG_PRODUCTCATALOGSERVICE=productcatalogservice
      - IMAGE_TAG_RECOMMENDATIONSERVICE=recommendationservice
      - IMAGE_TAG_SHIPPINGSERVICE=shippingservice
      # Adding the image url
      - sed -i 's@CONTAINER_IMAGE_ADSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_ADSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_CARTSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_CHECKOUTSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_CURRENCYSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_CURRENCYSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_EMAILSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_FRONTEND@'"$REPOSITORY_URI:$IMAGE_TAG_FRONTEND"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_LOADGENERATOR@'"$REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_PAYMENTSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_PRODUCTCATALOGSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_RECOMMENDATIONSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE"'@' release/kubernetes-manifests.yaml
      - sed -i 's@CONTAINER_IMAGE_SHIPPINGSERVICE@'"$REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE"'@' release/kubernetes-manifests.yaml
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build src/cartservice/src -t $REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE $REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE
#      - docker build src/checkoutservice -t $REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE
#      - docker tag $REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE $REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE
      - docker build src/frontend -t $REPOSITORY_URI:$IMAGE_TAG_FRONTEND
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_FRONTEND $REPOSITORY_URI:$IMAGE_TAG_FRONTEND
      - docker build src/loadgenerator -t $REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR $REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR
      - docker build src/paymentservice -t $REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE $REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE
      - docker build src/productcatalogservice -t $REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE $REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE
      - docker build src/recommendationservice -t $REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE $REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE
      - docker build src/shippingservice -t $REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE $REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE
      - docker build src/emailservice -t $REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE
      - docker tag $REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE $REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG_CARTSERVICE
#      - docker push $REPOSITORY_URI:$IMAGE_TAG_CHECKOUTSERVICE
      - docker push $REPOSITORY_URI:$IMAGE_TAG_EMAILSERVICE
      - docker push $REPOSITORY_URI:$IMAGE_TAG_FRONTEND
      - docker push $REPOSITORY_URI:$IMAGE_TAG_LOADGENERATOR
      - docker push $REPOSITORY_URI:$IMAGE_TAG_PAYMENTSERVICE
      - docker push $REPOSITORY_URI:$IMAGE_TAG_PRODUCTCATALOGSERVICE
      - docker push $REPOSITORY_URI:$IMAGE_TAG_RECOMMENDATIONSERVICE
      - docker push $REPOSITORY_URI:$IMAGE_TAG_SHIPPINGSERVICE
      # Upload a file to the S3 bucket
      - aws s3 cp release/kubernetes-manifests.yaml s3://microservices-demo-new/
      - kubectl apply -f release/kubernetes-manifests.yaml
      - kubectl delete --all pods --namespace=default
